nuita/nuita

app/controllers/users_controller.rb
app/models/user.rb
config/routes.rb
db/migrate/20190522140204_add_url_disgest_to_users.rb
db/schema.rb
lib/tasks/url_digest.rake
test/controllers/users_controller_test.rb
test/fixtures/users.yml
test/models/user_test.rb

#21 を解消
既存ユーザーにはurl_digestが設定されていないので、
```rake url_digest:set_url_digest```　とかやる必要ありそう
アイコンとかのパス変えるの大変そうなので、内部的にはまだ連番のIDが動いています……。

`/users/{ランダム文字列} ` にルーティング変更

---

app/controllers/application_controller.rb
app/models/user.rb
lib/tasks/twitter_task.rake
test/controllers/twitters_controller_test.rb
test/controllers/users_controller_test.rb
test/integration/autotweet_test.rb

fix #53
あとこれも治した
`twitter_task:disable_autotweet_with_no_account` で既存DBもいい感じに治せる

Fix twitter bugs

---

app/assets/javascripts/nweets.js
app/assets/javascripts/users.js
app/assets/stylesheets/custom.scss.erb
app/controllers/relationships_controller.rb
app/views/nweets/_follow_icon.html.slim
app/views/nweets/_nweet.html.slim
app/views/users/_follow.html.slim
app/views/users/_unfollow.html.slim
app/views/users/_user.html.slim
config/routes.rb
test/controllers/relationships_controller_test.rb
test/controllers/users_controller_test.rb
test/integration/followee_test.rb

- Relationshipsコントローラーを単数形リソースに変更 (id使わずにユーザーで指定したほうがajaxやりやすい……)
- タイムライン上のヌイートにフォロー／リムーブボタン追加 (闇ajax)
- ↑のボタンの形でFFは分かるけど、「一方的にフォローされている」を示すアイコンがないので中途半端
- いいやつないかな (できたらFont Awesomeで)

フォローボタンをタイムライン上のヌイートに表示

---

app/assets/javascripts/users.js
app/assets/stylesheets/custom.scss.erb
app/controllers/users_controller.rb
app/helpers/application_helper.rb
app/helpers/users_helper.rb
app/models/user.rb
app/views/nweets/_nweet.html.slim
app/views/users/_calendar.html.slim
app/views/users/_user_info.html.slim
test/controllers/users_controller_test.rb
test/fixtures/nweets.yml

射精をGitHubのContribution Graph風に表示することができるようになりました。  
当初思い描いていた機能はほぼこれで完遂できたので胸がいっぱいです。
スマホ対応はガバガバなので今後縦横回転させたりできるようにしたい
日にちをクリックするとその日のヌイート一覧が見られます。
相互なら他のユーザーのグラフも見に行けます。

Contribution graph

---

app/assets/stylesheets/custom.scss.erb
app/controllers/users_controller.rb
app/models/user.rb
app/views/devise/registrations/edit.html.slim
app/views/users/_user_info.html.slim
config/locales/ja.yml
test/controllers/users_controller_test.rb

いづれもユーザーの個人ページで見える情報の変更です。
- フォロー・フォロワーをフレンドに公開するようになりました。
- 自己紹介は上限30文字の「ひとこと」に変更され、全体へ公開されるようになります。
- グラフも全体へ公開されます。
他のユーザーに見せる情報について迷っていましたが、
- ヌイート(の分析)やオカズなど、**射精に直接関連する** 情報 -> **全体公開**
- フォロー／フォロワーやいいね、名前やtwitter垢など、 **射精には関係のない** 情報 -> 基本 **フレンドのみ公開** 、オプションで完全非公開
という感じでやっていけたらなあと思っています　

フォロー・フォロワーをフレンドに公開／自己紹介を全体公開の「ひとこと」へ

---

app/helpers/users_helper.rb
test/integration/devise_test.rb

原因はリライトしたicon_forでユーザーがまだ存在しないときの挙動とか考えてなかったことです
deviseの作ったページのテスト全然書いてなかったから追加した

新規登録画面表示できない不具合修正

---

app/controllers/nweets_controller.rb
app/views/nweets/_create_form.html.slim

https://github.com/nuita/nuita/issues/5
nweet作るのにいちいち
`nweets.build(did_at: Time.zone.now)`
ってやるのダサいからモデル側でdid_at入れるような感じにしようかと思ったけどテストとかvalidationもいじるはめになったからやめた
collaborator権限ください！！！

did_atがnweetボタン押したタイミングになるように修正 #5

---

app/models/link.rb
lib/tasks/category_task.rake
test/models/nweet_test.rb
test/models/user_test.rb

ヌイート中に「#R18G」とか入れるとタグ付けされる機能をこっそり実装していたんですが、勝手にカテゴリ作る機能も実装していたのを忘れていた
UI的にカテゴリ乱立するとしんどくなるので、とりあえずカテゴリの新規作成機能は削除、ただし既存のカテゴリに対してはタグ付け機能継続
`category_task:clean` で不要なカテゴリ（デフォルトで検閲機能ついてないやつ）を削除できるようになったので、本番で動かす

ヌイート中のハッシュタグに相当するカテゴリが存在しないときに自動生成する機能を削除

---

app/models/link.rb
lib/tasks/link_task.rake

メタタグが変わっていたらしく画像をしばらく読み取れていなかった
ついでにURL正規化を厳密にしたり ```rake link_task:refetch_melonbooks``` でデータ再取得できるようにしたりした
感想；リンクカード周りの現在の処理はすごくゴミ

Fetch melonbooks mk2

---

app/controllers/christmas_controller.rb
app/views/christmas/about.html.slim
app/views/christmas/show.html.slim
app/views/layouts/_user_header.html.slim
app/views/nweets/_nweet.html.slim
app/views/pages/_recommend.html.slim
config/routes.rb
test/controllers/christmas_controller_test.rb

本当はStamp関連のコードとか全部消すつもりでいたけど、
1月31日までは（バッジの有無が妥当かとか確認するために）アドベントカレンダー見れるようにしたからあんま消えなかった
- ホーム画面でのアドベントカレンダーの表示廃止
- ヘッダーの右メニューでのアドベントカレンダーへのリンク廃止
くらい

クリスマス関連の表示を除去

---

app/javascript/packs/follow_icon.ts
app/javascript/packs/nweets.ts
app/javascript/packs/pagination.ts

`addEventListener(turbolinks:load)` でいいねボタンの動作をDOMに紐付ける
-> `insertAdjacentHTML()` でfetchしてきたヌイート挿入する
-> 挿入されたヌイートにはいいねボタンとかの動作紐付けられてない
みたいなことだと思う
JSかなり雑なのでもっと賢く早くしたい……

スクロールしたあとのいいねボタン、フォローボタンにJS紐付いてなかったので修正

---

Gemfile
Gemfile.lock
app/models/link.rb
app/views/cards/_horizontal.html.slim
app/views/cards/_vertical.html.slim
db/migrate/20200117162634_add_image_sizes_to_links.rb
db/schema.rb
lib/tasks/link_task.rake
lib/tasks/nweet_task.rake
test/models/link_test.rb

オカズの画像サイズをURL取得時に確認→保存してimgタグの要素として表示
されるようになった。Nuita高速化活動の一環
`Link.image_width` = 画像横幅, `Link.image_height` = 画像縦幅
`rails task link_task:refetch_all`とかで既存画像のも大きさ取り直してこれるはずだけど、
一応幅ない場合も許容するようにviewとか書いてあります

オカズの画像サイズを覚えておいてimgタグ上に残す

---

app/assets/stylesheets/custom.scss.erb
app/controllers/nweets_controller.rb
app/controllers/pages_controller.rb
app/helpers/categories_helper.rb
app/javascript/packs/categories.ts
app/javascript/packs/pagination.ts
app/javascript/packs/recommend.ts
app/models/link.rb
app/views/cards/_categories.html.slim
app/views/cards/_collapse_button.html.slim
app/views/cards/_horizontal.html.slim
app/views/cards/_vertical.html.slim
app/views/layouts/application.html.slim
app/views/nweets/_create_form.html.slim
app/views/nweets/_edit_form.html.slim
app/views/nweets/_home_form.html.slim
app/views/nweets/_new_form.html.slim
app/views/nweets/new.html.slim
config/routes.rb
test/controllers/nweets_controller_test.rb

すっきり〜
- これまでは **"#nuita!"ボタンが押されたタイミング** で一旦無言投稿(`nweets#create`)→`/?success=true`でオカズとか付け足してた(`nweets#edit`)
- 今後は"#nuita!"ボタンを押しただけでは投稿されない： **コメントの投稿が終わったタイミング** でコメントつきで投稿される
- ボタンは単に`/nweet/new`(`nweets#new`)へのリンクに, `nweets#new`のフォームが `nweets#create` を呼ぶ
- ツイートするタイミングもズレる→コメントの中身がtwitterカードに反映できるようになる
- 共有ボタンからヌイートとかをサポートする上でもこっちのほうがやりやすそう
- 「感想を入力」って何？？？？？いまのオカズ投稿する文化に合わせる
- オカズのカテゴリーが投稿時に設定できるようになった
- 将来的にプレビュー機能も実装したい
- 上のカテゴリー付きのフォーム作るときの副産物
- BootstrapのCSSのおかげで、わりとかっこいい感じの遷移のしかたする
- ほかのいいねボタンとかもtransitionのアニメーションつけたほうがかっこよくなるかも

新しいヌイート投稿画面

---

app/views/devise/confirmations/new.html.slim
app/views/devise/passwords/edit.html.slim
app/views/devise/passwords/new.html.slim
app/views/devise/registrations/edit.html.slim
app/views/devise/registrations/new.html.slim
app/views/devise/sessions/new.html.slim
app/views/devise/unlocks/new.html.slim
app/views/nweets/_new_form.html.slim

form_withだと画面遷移させるために`local: true`って指定しなきゃいけなかった

フォームの投稿後に画面遷移しない問題を修正

---

app/assets/javascripts/manifest.json.erb
app/views/nweets/_new_form.html.slim

`/nweets/new?text=` でテキストを埋められるようにして、そこにPWAの共有機能で閲覧しているウェブサイトのURLを渡せるようにしました。
動作確認してないので、なんか環境あったら試してもらうと良さそう。

PWAのシェアメニューに対応させる

---

app/assets/javascripts/manifest.json.erb

fix: https://github.com/nuita/nuita/issues/127
https://github.com/nuita/nuita/pull/126 で足したんですが、ちょっと動作確認出来てなかったところ動いてなかった。
今回は気合い入れて手元に開発環境立てて、portfowardして手元のAndroid Chromeで様子を見たので大丈夫そう。

[PWA]Chromeはurlは空でtextにページのURLが入る

---

app/controllers/links_controller.rb
app/frontend/src/recommend.ts
app/models/link.rb
app/views/pages/_recommend.html.slim

ランディングページでは
- 画像なしのオカズ
- カテゴリ(R18G,3D...)つきのオカズ
が最初から表示されなくなる。
ただし、自分から更新ボタンを押した場合には通常通り全てのオカズから表示される。

ランディングページのランダムえっちに表示されるオカズを制限

---

Gemfile
app/helpers/application_helper.rb
app/views/cards/_horizontal.html.slim
app/views/cards/_vertical.html.slim
config/initializers/camo.rb

#144 の続き
ヘルパー `camo_url` を使うと環境に応じていい感じにurl振り分けてくれるよ

Camoを本番環境でしか使わないようにする

---

app/helpers/application_helper.rb

camo使う範囲をhttp通信に限定

---

app/views/nweets/_nweet.html.slim

こっちのほうが画像大きくなって必要スクロール数増えるから、場合によってはtwitterとかPixivみたいに一部を切り出したほうがいいかも

ヌイート内のカードを縦から横に変更

---

app/models/nweet.rb
test/models/link_test.rb
test/models/nweet_test.rb

- fetch自体には成功しても、active_recordに書き込むタイミングでミスることがある（特殊文字とか）
- ヌイート側にも例外処理のところ作ってオカズの取得に失敗してもヌイート自体は投稿できるようにした

オカズの取得に失敗してもヌイート自体は投稿できるようにする

---

app/models/link.rb
config/deploy.rb

Link.refetch(), link_task::refetch_all がfetch_from使う形式に適用できてなかったので書き換えた
refetch()は今後rakeタスクから以外は使わないようにする

Link.refetch()をリライト

---

lib/tasks/link_task.rake

- `p link` で全レコード表示するのをやめて数字だけにした（エラーを目立たせるため）
- 個別サイトへの `refetch_***` も例外処理いれて最後まで回すようにした

link_task:refetch_*** の実行時のエラーをわかりやすくする

---

app/views/nweets/_nweet.html.slim

コメント付きの投稿増えるきっかけになってほしいなというあれ
嫌な感じになってたら元の仕様に戻すかも

フォロー中以外のユーザーのstatementもタイムラインで表示

---

app/controllers/pages_controller.rb
app/frontend/packs/application.ts
app/frontend/src/infinite_scroll.ts
app/views/pages/_timeline.html.slim

close #112
単に個数をずらしていくページング処理だと難しそうだったので、最後のヌイートより古いものを取得する処理を実装してみました
流れとしてはフロント側でDOMから取得した最も古いヌイートのIDをパラメータで渡して、そのヌイートより古いものを描画するような形です
ID取得がDOMに依存してたり、コントローラーの分岐があまりエレガントではないですが、問題がなさそうなら他の箇所も実装していきます
それからページング処理に関する部分は、おそらく無限スクロールを実装する前の名残のように見えたので、特に残さずに取り除きました

無限スクロール用の読み込み処理を改善

---

app/views/nweets/new.html.slim

投稿画面とタイムラインでレイアウトが異なるので、タイムラインに合わせる
おそらく投稿画面のみ #119 で変更し忘れたもの
現状

投稿画面のレイアウトをタイムラインに合わせる

---

app/views/devise/registrations/edit.html.slim

なんでコメントアウトされたまま放置されてたのか分からないけど close #156
UIは他の要素に合わせてこんな感じ
処理は特に触ってないけど、動作も特に問題なさそう
ただChromeの補完がusernameをキーにして保存してしまうみたいで、ログイン時に弾かれてしまう。autocomplete周りを若干調べてみたけども対処方法が見つからなかった
ID(username)でログインできるようにしてしまうのが確実かもしれない

パスワードを変更できるようにする

---

app/controllers/pages_controller.rb
app/controllers/users_controller.rb
app/frontend/src/infinite_scroll.ts
app/views/nweets/_nweets.slim
app/views/pages/_likeline.html.slim
app/views/pages/_timeline.html.slim
app/views/users/_feed.html.slim

ページで1つのinfiniteScrollContainerを使い回す代わりに、描画ごとにinfiniteScrollContainerを出力して、それと置き換える形で読み込むことによって、クエリをRailsのView側から属性を介して出来るようにした
なるべく念入りに調査した限りは特に問題はなさそうだったけど、割と複雑な変更だからエッジケースで問題が起きる可能性はありそう
今の所分かっている動作の違いは、変更前は20件ずつ読み込んでいたのが10件ずつになって、スクロール時に底に着く回数が増えた。UX的にobserverのmarginを増やすか、読み込む件数を増やしたほうが良いかも
原因としてはIntersectionObserverが初回と見えなくなったタイミングでもcallbackを実行しているみたいで、毎回containerを置き換えると読み込みが止まらなくなってしまうから、見えているときだけに制限した

無限スクロールに関する処理をRails側に移動

---

tsconfig.json

本番でtsのコンパイルに失敗してるなと思ったら、ES6以降の文法を使ってるのにtsconfig.json更新できてないのが原因らしいので、更新する
基本的にWebpackerが生成した初期設定に乗っかるようにしてるけど、適宜自分たちで変更を入れてかなきゃだめっぽい

tsconfig.jsonのlib指定をes2019にする

---

app/views/nweets/show.html.slim
app/views/users/likes.html.slim
app/views/users/show.html.slim
app/views/users/show_follow.html.slim

fix #193
なぜかbootstrap 4.5.0から`.col-md-3`と`.col`が並ぶとレイアウトが崩れるみたい
色々試してみたら`.col`の代わりに`.col-md`を使うと崩れなくなったから、見つけた限りは修正した
bootstrap的に何が正しいのか、それとも単なるバグなのかよく分からない
もしかしたら他にも崩れてるページがあるかも

レイアウトが崩れているのを修正

---

Gemfile
Gemfile.lock
config/deploy.rb

- CapistranoのバージョンとCapfileの指定が不整合してたので修正
- 致命的なあれにならない限りしばらくGemfileで固定しちゃう

Capistranoをアップデート、バージョン固定

---

app/assets/stylesheets/custom.scss.erb

ログインページのほかに新規登録ページと、プロフィール編集ページのズレが修正された
before
after

ログインフォームとかが右にずれるのを修正

---

app/controllers/tags_controller.rb
app/views/cards/_edit_modal.html.slim
app/views/cards/_edit_modal_tags.html.slim
app/views/cards/_renew_modal_tags.js.slim
app/views/cards/_tags.html.slim
test/controllers/tags_controller_test.rb
test/fixtures/links.yml

<s>現状見た目だけできてる状態</s> うごく close: #200 
実際のカードを見ながらいじれるようにしようと思ったけど、モーダルでやると領域足りなくて大変かもしれない
- とりあえずプレビュー無しでタグ一覧だけ表示されるようにした

ヌイート詳細画面からタグ一覧をいじれるようにする

---

app/controllers/censorings_controller.rb
app/controllers/nweets_controller.rb
app/helpers/tags_helper.rb
app/models/user.rb
app/views/cards/_edit_modal.html.slim
app/views/cards/_tags.html.slim
app/views/devise/registrations/_edit_censoring_modal.html.slim
app/views/devise/registrations/_edit_censoring_modal_tags.html.slim
app/views/devise/registrations/_renew_modal_tags.js.slim
app/views/devise/registrations/edit.html.slim
app/views/nweets/_new_form.html.slim
config/routes.rb
test/controllers/censorings_controller_test.rb
test/controllers/nweets_controller_test.rb
test/integration/censoring_test.rb

close #201 
TagsHelper#visible_tagsを削除するのが目標で始めたけど、設定画面もこれに依拠してたからモーダルで作り直すことになった
cards/edit_tag_modalと大部分が似てるから共通化できそう。別のPRで出すかも

R18Gと3D用のUIを削除、検閲するタグを設定画面から選択できるようにする

---

app/helpers/application_helper.rb

接続先がhttpsでもキャッシュサーバ代わりにcamo使う close #175

外部サイトの画像には常にcamo使う

---

Gemfile.lock
app/helpers/application_helper.rb
app/models/tag.rb
lib/tasks/link_task.rake
test/models/preference_test.rb

外部サイトに合わせてタグの名称を変更、検閲を追加
- 名称変更：R18G→R-18G, 3D→3次元
- 検閲追加：全ユーザーの検閲タグに「スカトロ」追加
- 検閲削除：新規ユーザーからは「3次元」(3D)の検閲外す

デフォルトの検閲タグを増やす＆一部の名称変更

---

app/views/cards/_edit_modal.html.slim
app/views/cards/_edit_modal_tags.html.slim
app/views/cards/_renew_modal_tags.js.slim
app/views/devise/registrations/_edit_censoring_modal.html.slim
app/views/devise/registrations/_edit_censoring_modal_tags.html.slim
app/views/devise/registrations/_renew_modal_tags.js.slim

- オカズにタグが1件も紐付けられていないときにタグ一覧のスペースに「タグが設定されていません」的な文字を表示する
- タグを新規追加したときにinputの中身を消去する（自動で消えてくれると思ったけど、そうでもなかったっぽい……）

改善されたモーダルのUI

---

app/helpers/application_helper.rb

camoしばらくはいい感じだったんですが、現状PixivとKomiflo取りにいくの失敗してるみたいです（もしかしたらブロッキングされてるかも）。
[camo自体にキャッシュ機能はない](https://qiita.com/tomoasleep/items/6b50445d5a5eac06f7a8)っぽい話もあるので、一旦camoの使用をhttp画像のプロキシに限定します。
キャッシュ自体は何らかの形でちゃんとやらなきゃいけない……。

一旦camoの使用をhttpサイトのプロキシに限定する

---

.github/workflows/test.yml

> ActionView::Template::Error: Autoprefixer doesn’t support Node v8.10.0. Update it.
って出るため

CIで使用するnodejsのバージョンを上げる

---

Gemfile
Gemfile.lock
config/environments/development.rb

C実装のsassコンパイラを使うから今までより早いらしいよ
手元で動かした限りは問題なさそう

非推奨のsass-railsをsassc-railsに変更

---

Gemfile
Gemfile.lock
app/helpers/application_helper.rb
app/views/cards/_horizontal.html.slim
app/views/cards/_vertical.html.slim
config/initializers/camo.rb
docker-compose.yml

試してみたら結構簡単に出来たのでとりあえずPRを投げておく
とりあえずメモリに200MB、最大4時間のキャッシュをする設定にしてみたけど、たぶん調整が必要
- README見てたらメモリの他にディスクとかs3とか、更にオープンソースなs3のクローンも使えるみたい
secretkeyに関してはRailsが入ってないコンテナから読む必要があるので、(開発時用のデフォルト値へのフォールバックありで)環境変数経由で渡すか、(実装がめんどくさそうだけど)やろうと思えばcredentials.yml.encから読み出すこともできるかもしれない（方針が決まったら対応する）
- docker内に入れてしまうから開発環境でも使えることには使えるけど、アクセスするアドレスが一定ではないから注入するのが大変そう（デフォルトでlocalhostにしておいてrails起動時の環境変数で変えられるようにするとか？）
URLを生成するコード(どこに書くのが正解か分からなかった)：
```rb
require 'openssl'
require 'base64'
KEY = "secret"
HOST = "http://localhost:8080"
def proxy(url)
digest = OpenSSL::HMAC.digest(OpenSSL::Digest.new('sha256'), KEY, url)
signature = Base64.urlsafe_encode64(digest).strip()
"#{HOST}/s#{signature}/#{url}"
end
```

imageproxyを導入

---

app/assets/stylesheets/custom.scss.erb

`width: 100vw;`を使うとスクロールバーを考慮せずにはみ出してしまう
でもなんで今ままで気づかなかったんだろう。特に直近の変更なさそうだったし

ランディングページのはみ出しを修正

---

.github/workflows/test.yml
docker-compose.yml

- 開発環境 (Docker) やテスト (GitHub Actions) で使うMySQLのバージョンを、<del>README</del> https://github.com/nuita/nuita/pull/261#issuecomment-699986288 にあるバージョンに合わせました
- `image` にtagを指定しないと `mysql:latest` が使われて、開発環境のDBだけどんどんバージョンアップしてしまう気がする
- [MySQL 8.0はメンテナンスバージョンアップにがんがん機能追加・削除を入れてくる](https://speakerdeck.com/yoku0825/mysql-8-dot-0nifu-kenaitesutofalsezuo-rifang-jia?slide=15)という話もある
- 本番と開発環境で挙動が違うと難しいのでできるだけ環境を揃えたい
- テストだけMySQL 5.7を使ってた
- docker-compose.yml
- Dockernizeされた開発環境を初期化して `docker-compose run --rm app rails test` が通る
- GitHub Actions
- CIのテストが通る
- READMEに書いてある各種アプリケーションのバージョンが本番環境のものなのか、推奨環境がこうなっているのか分かりませんでした。ひとまず本番環境のバージョンだと思ってcommit messageを書きましたが、もし違っていたらご指摘いただきたいです
- そのようにcommit messageを修正します

開発環境のMySQLのバージョンを本番環境に合わせる

---

app/views/layouts/application.html.slim

Font Awesome5からデフォルトになったらしい(?)JS+SVG形式の利用を試してみたのですが、
いいねボタン押したときの処理が旧DOM構造に依存してたので、JS+SVG形式の利用は一旦差し戻します

font-awesomeの指定を一時的にCSSに戻す

---

app/helpers/application_helper.rb

s3のuriを返そうとしてるところが後ろに余分にurlがあるせいで常に元のurlを返すようになってしまっています。

fix always returns url

---

app/frontend/src/header.ts

Safariとかの画面上に引っ張る動作によってヘッダー壊れてたみたいです。
ちゃんと検証してなかった……問題報告＆対応ありがとうございました。

fix: ページ上端からさらに上スクロールしたときにヘッダー壊れる問題を修正

---

.github/workflows/test.yml

自分でうっかり書いてるのかと思ったけど、依存してるsetup-rubyが古いせいだった
ので常に最新版使うようにした（バージョン固定してる理由何かあったっけ・・・？）

Actionsでset-env使わないようにする

---

.rubocop.yml
app/models/user.rb
test/models/user_test.rb

ちゃんと元記事を読んだら、バリデーションの仕様が変わるというだけで、DBの照合順序自体は元からcase insensitiveでした。（手元＆本番SQL確認しましたが、どちらも元々そうだった）
なので、DBのunique制約は変わらないままだから、`unique: {case_insensitive: false}` ってやっちゃってよさそう。

close #292

---

app/views/nweets/_home_form.html.slim
app/views/nweets/_new_form.html.slim
app/views/nweets/new.html.slim
app/views/nweets/new.js.slim
app/views/pages/_user_home.html.slim

new.js.slimでnew_formを動的に挿入したときと、直接nweets/newを開いたときとで微妙にDOM構造が異なっていたため、余白やなんやに影響が出ていたので、new.js.slimのターゲットをformの外に出すことで解決します。

new.js.slimとnweets/newの不整合を修正

---

app/assets/stylesheets/custom.scss.erb

劇長い単語がカードに含まれてると幅足りなくなって崩れるっぽい

カラム崩れる問題を修正

---

app/models/link.rb
app/views/cards/_horizontal.html.slim

そもそもモデル側での文字数制限いるか？という感じではある
一旦既存の制約に合わせてhash_panchiraで短くする処理を行い、view側でさらに切り詰めて使う

取得したオカズのテキストをバリデーション以下の文字数まで切り詰める

---

app/controllers/application_controller.rb
app/models/nweet.rb

タイムライン表示用に関連テーブルを一括読み込みするNweet#includedというスコープを用意していましたが、
Railsの名前と衝突しているという最悪の事態だったので適当にリネームしました。

Nweet#includedを#relations_includedに改名

---

app/controllers/application_controller.rb
app/controllers/nweets_controller.rb

[application_controllerの不具合？ #296](https://github.com/nuita/nuita/issues/296) の対応
https://github.com/nuita/nuita/blob/0266f222edc1f3f41d5e0917f8a3da40f57bb9f5/app/controllers/application_controller.rb#L19-L21
`current_user?` については使用されていないため削除
同様の
https://github.com/nuita/nuita/blob/0266f222edc1f3f41d5e0917f8a3da40f57bb9f5/app/helpers/users_helper.rb#L32-L34
についても使用されていないため削除しようかと思ったが、
1. 今回の対応範囲（application_controller.rb）ではないこと
2. helperメソッドならいつか使うかもしれないこと
から保留
nweetオブジェクトを元にツイート文を生成するメソッドの引数が使われていないとのことなので、その辺りの整理
- nweet オブジェクトを元にツイート文を生成するのでとりあえず nweets_controller.rb へ移動
- ツイート時に本文が `nil` または空の場合はツイッター側でエラーが出るはずなので、本文なしの場合はツイートを実行しないよう急場しのぎの対応
取り組んでいて気づいたが、`User.autotweet_content` が empty となることを許容しているのは問題かと思われる。
（ツイッターは本文なしで投稿するとエラーが出るはずなので）
別イシュー立てる等して対応したい。

application_controller.rb 周りのリファクタ

---

app/frontend/css/components/navbars/_user_navbar.scss
app/frontend/css/nweets/_form.scss
app/frontend/packs/application.ts
app/frontend/src/new_nweet_form.ts
app/views/nweets/_new_form.html.slim
tsconfig.json

テキストボックスに文字数カウントを追加しました。
絵文字はサーバー側では1文字としてカウントされてますが、見ての通り2文字扱いを受けています。
これはRails側で生成されるフォームの仕様に合わせたためで、将来的にフォームのmaxlengthの挙動含め変更する必要がありそうです。
```<textarea maxlength="100" rows="2" class="new-nweet-form-textbox form-control" id="newNweetFormTextarea" placeholder="感想・使用したオカズを入力（100文字以内）" name="nweet[statement]"></textarea>```

文字数カウント機能を実装

---

tsconfig.json

requireがないって言われるので、node関連の読み込みがちゃんとできてないっぽい？
cf: https://github.com/rails/webpacker/issues/1276

TSのコンパイル通らないのでtsconfigの記述を追加

---

test/fixtures/links.yml
test/fixtures/nweet_links.yml
test/fixtures/nweets.yml
test/models/like_test.rb
test/models/link_test.rb

`like_test.rb`, `link_test.rb` にあるfeaturableに関するテストで実URLへのアクセスをやめ、fixtureへと変更しました。
Github上での実URL取得がうまく行ってないのか、手元で成功していもたびたびテストが失敗していたためです。
本来外部URLへのアクセスは全部mockなりfixtureなりに置き換えたほうがいいかとは思うんですが、
それはそれで外部との接続の層のテストができないので恐ろしいです。
「外部へアクセスできる」程度のものだけ数を絞って置いておこうと思います。

featurableに関するテストで実URLへのアクセスをやめ、fixtureへと変更

---

test/models/link_test.rb

やっぱり定期的に落ちるので、外部URLにアクセスするテストをさらに減らしました。
この辺はカードあり/カードなしで2パターン試してるつもりだったけど、そのへんはpanchiraの側で担保されてるからテストしなくて大丈夫だと思いこむことにする……

外部urlにアクセスしてるテストをさらに減らす

---

app/frontend/packs/application.ts
app/frontend/src/modal.ts
app/views/cards/_tags.html.slim

Bootstrapのモーダルはposition: fixed; とかの親要素の下だと正常に動かないようなので、モーダルの表示時にだけ動的にbody直下にノードを移し替えることにしました。
モーダルの閉じるボタンが動かない問題もひそかに発見してたんですが、この修正で問題なく動くようになってそう。
https://stackoverflow.com/questions/10636667/bootstrap-modal-appearing-under-background

モーダル表示時にbody直下にノードを移す

---

app/models/nweet.rb
app/views/nweets/_new_form.html.slim
db/migrate/20210529135837_change_nweet_statement_length.rb
db/schema.rb
test/models/nweet_test.rb

close: #202
ユーザーアンケートの結果でも文字数制限がストレスになってそうな気配があったので、一旦200文字までに変更します。

ヌイートの文字数制限を最大200文字に変更

---

app/controllers/application_controller.rb
app/controllers/pages_controller.rb
app/frontend/css/nweets/_form.scss
app/frontend/css/nweets/_nweet.scss
app/frontend/src/new_nweet_form.ts
app/helpers/nweets_helper.rb
app/models/nweet.rb
app/views/nweets/_new_form.html.slim
app/views/nweets/_nweet.html.slim
config/locales/views/nweets/ja.yml
test/controllers/pages_controller_test.rb
test/fixtures/nweets.yml
test/models/nweet_test.rb

close #29 
過去の日時を指定してヌイートできるようになりました。射精時刻は did_at, 投稿時刻は created_at として区別されます。この2つの時刻を区別しやすくするために、投稿時刻の表示もやや変更しました。
Chromeの開発者ツールで見ると小画面でフォームが崩れますが、実機では再現しなかったのでたぶんいけるやろの精神でPRを出します。

過去の日時を指定してヌイートできるようにする

---

app/controllers/nweets_controller.rb
test/controllers/nweets_controller_test.rb
test/models/badge_test.rb

間違って射精時刻の修正ボタンを押してしまい、投稿時刻とほぼ同じなのに注釈がついちゃってる投稿を何個か見つけたので実装しました。
ついでにバッジ機能のテストも削除しています（使い所ないので）

ユーザーの指定した射精時刻が3分以内の場合は投稿時刻と同一にする
