nuita/nuita

- Capfile
- Gemfile
- Gemfile.lock
- config/deploy.rb
- config/deploy/production.rb
- config/deploy/staging.rb
> なんかよく分からないけどcapistranoつかってみる

- app/views/devise/registrations/edit.html.slim
- app/views/devise/registrations/new.html.slim
- app/views/devise/shared/_links.html.slim
- app/views/layouts/application.html.slim
- config/locales/devise.ja.yml
- config/locales/ja.yml
> Japanese devise

- app/models/user.rb
フォローとかフォロワーとか実装できたらたぶん変わる　ヌイート全部取ってきてるから小規模のうちしか持たないはず
> とりあえずホームを全体タイムラインに

- app/assets/javascripts/pages.js
- app/assets/stylesheets/custom.scss.erb
- app/controllers/nweets_controller.rb
- app/helpers/nweets_helper.rb
- app/models/nweet.rb
- app/views/nweets/_create_form.html.slim
- test/controllers/users_controller_test.rb
- test/fixtures/nweets.yml
- test/fixtures/users.yml
- test/models/nweet_test.rb
fix #13 .
3分以内に連続射精は……………………たぶん無理だと思ってるんだけど………………どう？
（本当は3分経ったら[というかRails側でvalidになったら]ボタンをenableしたい　という気持ちがあり、そろそろフレームワーク的なやつを導入してもいいかもしれない）
> 3分以内の連続投稿を禁止

- app/controllers/application_controller.rb
- app/controllers/nweets_controller.rb
- app/helpers/users_helper.rb
- test/controllers/nweets_controller_test.rb
> ヌイートの作成と削除は正しいユーザーだけ行える

- app/assets/stylesheets/custom.scss.erb
- app/controllers/nweets_controller.rb
- app/controllers/pages_controller.rb
- app/models/nweet.rb
- app/views/nweets/_create_form.html.slim
- app/views/nweets/_edit_form.html.slim
- app/views/nweets/_nweet.html.slim
- app/views/pages/_user_home.html.slim
- config/routes.rb
- db/migrate/20190504173055_add_statement_to_nweets.rb
- db/schema.rb
- test/controllers/nweets_controller_test.rb
- test/fixtures/nweets.yml
- test/models/nweet_test.rb
> ヌイートに文章を追加

- app/assets/stylesheets/custom.scss.erb
- app/helpers/application_helper.rb
- app/views/nweets/_nweet.html.slim
あんま考えたくないけど（考えられないので）、ブラクラ的なやつの対策しなきゃいけないかもしれない
将来的にはtwitterとかSlackみたいにカード生成したい
> statement中のURLをハイパーリンクとして表示

- Gemfile
- Gemfile.lock
- app/assets/javascripts/application.js
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/custom.scss.erb
- app/helpers/application_helper.rb
- app/views/layouts/_header.html.slim
- app/views/layouts/application.html.slim
- app/views/pages/_user_home.html.slim
合わせてNavbarとPaginateも書き直した
Navbarのトグルボタンはそのうちユーザーアイコンにしたい
> Bootstrap4

- app/views/devise/registrations/new.html.slim
- app/views/users/show.html.slim
- サインアップ画面をいい感じにbootstrap化
- ユーザー詳細画面では小画面でもユーザー情報を表示する
> もっとシュッとした感じのview

- Gemfile.lock
- app/assets/stylesheets/custom.scss.erb
- app/views/nweets/_nweet.html.slim
- app/views/nweets/show.html.slim
> Iikanji view

- app/controllers/users_controller.rb
- app/views/pages/_favline.html.slim
- app/views/users/_user_info.html.slim
- app/views/users/likes.html.slim
- config/routes.rb
/i/favorites を廃止、ユーザーごとに/likes/でいいね一覧が見られるように
非表示オプションとかはまた後で考えます
> 他のユーザーのいいね一覧が見られるようになった

- app/helpers/application_helper.rb
> ヌイート中のリンクは別タブで開く Close #45

- app/views/layouts/application.html.slim
- app/views/nweets/show.html.slim
ツイッターへの投稿はヌイートの内容編集より先（nuitaボタン押した瞬間）だから、これだけだとうまく反映されないかも
> Descriptive twitter card

- Gemfile
- Gemfile.lock
- app/assets/stylesheets/custom.scss.erb
- app/controllers/links_controller.rb
- app/helpers/application_helper.rb
- app/models/link.rb
- app/models/nweet.rb
- app/models/nweet_link.rb
- app/views/nweets/_nweet.html.slim
- config/routes.rb
- db/migrate/20190716100407_create_links.rb
- db/migrate/20190719135706_create_nweet_links.rb
- db/schema.rb
- test/controllers/links_controller_test.rb
- test/fixtures/links.yml
- test/models/link_test.rb
- test/models/nweet_link_test.rb
- test/models/nweet_test.rb
失敗してるわけではないんですが、twitter用のメタタグの情報拾ってきてるだけなので、  
サイトによってはアイコン表示されたり画質粗かったりします
主要なサイトは個別のコード書いて精度上げてからリリースしようと思います
> リンクをカードとして表示

- app/models/nweet.rb
- test/models/nweet_test.rb
> 既存のURL出てきたときに関連付けしてカード表示できるようにした

- app/models/link.rb
- test/models/link_test.rb
> Fetch pixiv

- app/models/link.rb
- test/models/link_test.rb
> Melonbooks

- test/integration/favline_test.rb
そろそろテスト期間だから、不足してるテストを書きまくろうと思う
> [WIP]そろそろテスト期間だし

- Gemfile
- Gemfile.lock
- app/assets/javascripts/nweets.js
- app/assets/stylesheets/application.css.scss
- app/assets/stylesheets/custom.scss.erb
- app/views/layouts/_user_header.html.slim
- app/views/nweets/_nweet.html.slim
- app/views/users/_user_info.html.slim
close: #37 
font-awesome-rails使うのやめてfont-awesome-sassにした
ちょっと上下に揃った気がする？
けどPRO版でしか使えないスタイル多すぎるしまた乗り換えるかもしれない
（'fa-heart'と'fa-external-link'の線の太さ違ってちょっと気持ち悪い……）
> Font Awesome 5

- Gemfile
- Gemfile.lock
- config/database.yml
- db/schema.rb
- test/models/nweet_test.rb
「MySQLの制約で絵文字が使えない→タイトルとかに絵文字含まれてるリンクを共有できない」問題を修正したついでに全部の環境でMySQL使うようにした
なんか同じPRでやるべきじゃなかった気がするけど……
close: #56
> テスト、開発環境でMySQL使う + 絵文字対応

- app/controllers/application_controller.rb
- app/views/devise/registrations/edit.html.slim
- app/views/users/_user_info.html.slim
- config/locales/ja.yml
- db/migrate/20190817100841_add_biography_to_users.rb
- db/schema.rb
- db/seeds.rb
- test/controllers/users_controller_test.rb
- test/fixtures/users.yml
- プロフィールに自由記述のBiography(100文字程度)追加
- FFだと見られる
- twitterアカウントはFFじゃなきゃ見れなくなった
> 自由記述のユーザープロフィールを追加

- app/views/nweets/_card.html.slim
- app/views/nweets/_favorite_form.html.slim
- app/views/nweets/_nweet.html.slim
> ヌイートのviewをパーシャル化

- app/views/nweets/_nweet.html.slim
- config/application.rb
- test/fixtures/nweets.yml
 contribution graph作るための副産物、一旦これだけデプロイして壊れないか実験してみる
将来的にはユーザーごとにタイムゾーン変えられるようにできるはず
> config.timezone 設定

- app/assets/stylesheets/custom.scss.erb
- app/models/link.rb
- app/views/cards/_horizontal.html.slim
- app/views/cards/_vertical.html.slim
- app/views/layouts/_header.html.slim
- app/views/layouts/application.html.slim
- app/views/nweets/_card.html.slim
- app/views/nweets/_nweet.html.slim
- app/views/nweets/show.html.slim
- app/views/pages/_random.html.slim
- app/views/pages/_user_home.html.slim
- app/views/users/_user_info.html.slim
- app/views/users/likes.html.slim
- app/views/users/show.html.slim
- app/views/users/show_follow.html.slim
container-fluidにして中央カラムのmarginも削ったのでスマホ上の見栄えもよくなったはず・・・
右カラムには適当にランダムなオカズを1件載せてますが、
苦手な画像がいきなり出てくる可能性あるから対策したほうがいいかも
> 大画面でのレイアウトを3カラムに変更

- app/assets/javascripts/application.js
- app/assets/stylesheets/custom.scss.erb
- app/views/cards/_horizontal.html.slim
- app/views/cards/_vertical.html.slim
- app/views/pages/_landing.html.slim
- app/views/pages/_random.html.slim
Bootstrapのツールチップ思ったより簡単に使えた
UIの分かり度が全然変わってくるし今後どんどん増やしていく……
> ランダムえっちをランディングページに表示

- app/views/users/_user.html.slim
- db/seeds.rb
ユーザー一覧画面で他ユーザーのbiographyも表示されるようになった
> Slightly different userlist

- app/controllers/notifications_controller.rb
- app/javascript/packs/notification.ts
- app/javascript/packs/recommend.ts
- app/views/layouts/_user_header.html.slim
- app/views/layouts/application.html.slim
- config/routes.rb
> 通知をpollingで一定秒ごとに取ってくる

- app/assets/stylesheets/custom.scss.erb
- app/javascript/packs/nweets.ts
- app/models/like.rb
- app/views/nweets/_like_flash.html.slim
- app/views/nweets/_like_form.html.slim
- db/migrate/20191101164435_add_latest_liked_time_to_nweets.rb
- db/schema.rb
- test/models/like_test.rb
> いいねの総数表示を廃止、代わりにいいねされた最新時間を表示

- Gemfile
- Gemfile.lock
- app/views/devise/registrations/edit.html.slim
We found potential security vulnerabilities in your dependencies.
You can see this message because you have been granted access to security alerts for this repository.
> omniauthの脆弱性回避(GET送っちゃいけないらしい)

- app/models/link.rb
- lib/tasks/link_task.rake
- test/models/link_test.rb
> Fetch pixiv mk2

- app/models/user.rb
- lib/tasks/christmas_task.rake
`rake christmas_task:give_badges`
たいへん長らくおまたせしました、たぶんこれでいけてると思う
> christmas_task:give_badges

- app/javascript/packs/pagination.ts
> 二重読み込みやめさせる

- app/controllers/categories_controller.rb
- app/javascript/packs/categories.ts
- app/javascript/packs/recommend.ts
- app/views/cards/_categories.html.slim
検閲とか実装できてなかったので　いい感じになったらもとに戻す
> 既存ヌイートのカテゴリー設定にはajax使わない

- app/assets/stylesheets/custom.scss.erb
- app/views/notifications/index.html.slim
- app/views/nweets/new.html.slim
- app/views/nweets/show.html.slim
- app/views/pages/_user_home.html.slim
- app/views/users/likes.html.slim
- app/views/users/show.html.slim
- app/views/users/show_follow.html.slim
> More brand colors

- Gemfile
- Gemfile.lock
- app/assets/javascripts/application.js
- app/assets/stylesheets/custom.scss.erb
- app/javascript/packs/header.ts
- app/javascript/packs/notification.ts
- app/javascript/packs/pagination.ts
- app/javascript/packs/recommend.ts
- app/javascript/packs/user_info.ts
- app/views/layouts/application.html.slim
Webpacker外し活動の一環
フロントエンドいい感じに分離したい……
> No turbolinks

- app/models/link.rb
- app/models/nweet.rb
- app/models/resolvers/dlsite_resolver.rb
- app/models/resolvers/komiflo_resolver.rb
- app/models/resolvers/link_resolver.rb
- app/models/resolvers/melonbooks_resolver.rb
- app/models/resolvers/nijie_resolver.rb
- app/models/resolvers/pixiv_resolver.rb
- config/application.rb
- test/models/link_test.rb
- test/models/nweet_test.rb
close: #66 
まだURLに対してResolver振り分ける処理が残ってるの若干気持ち悪いけど、
とりあえずサイトごとにクラス分けただけでだいぶいい感じになったから一旦PR出す
たぶんそのResolverで処理できるかをResolver.resolvable(url)みたいな関数に切り分けて、/app/model/resolver/以下をglobでいい感じに読み込んだりしたら↑の処理も抽象化できそう
> Link.rbのリファクタリング

- app/models/nweet.rb
- test/integration/censoring_test.rb
#148 はリンク作られない条件を間違えてて全然テスト通らなかったので修正
> リンク作られない条件をミスってたので修正

- app/models/resolvers/dlsite_resolver.rb
- app/models/resolvers/link_resolver.rb
- test/models/link_test.rb
DLSiteの読み取りが正しくされてなかった問題を修正、例外発生時にも読み取れたタイトルはそのまま使う
> Fix dlsite resolver

- app/models/link.rb
> 何って……selfをつけ忘れただけだが？

- app/views/pages/_recommend.html.slim
- test/controllers/notification_controller_test.rb
- Link.displayable導入したのに、表示できるリンクがあるかどうかはLink.any?で判定していた。
- あとどうしても通らないnotification_contoller_testを1個削除した（小声）
> テスト環境だとpages#homenot

- app/assets/stylesheets/custom.scss.erb
- app/views/pages/_landing.html.slim
> ランディングページのレイアウトを修正

- app/frontend/packs/application.ts
- app/frontend/src/infinite_scroll.ts
> イベントの紐付けタイミングを修正

- app/controllers/nweets_controller.rb
> 投稿ページの無限スクロールバグを修正

- app/frontend/src/header.ts
もはや環境が変わりすぎて、元のissueと関係ないような気もするけど close #41
> トップに戻るアニメーションが動くように修正

- tsconfig.json
> esnext使うようにtsconfig.json変更

- app/views/notifications/index.html.slim
> 通知がないときのメッセージが表示されるように修正

- Gemfile
- Gemfile.lock
- app/assets/javascripts/application.js
- app/assets/stylesheets/application.css.scss
- app/views/layouts/application.html.slim
> flashをトーストとして表示させる

- Gemfile
- Gemfile.lock
- app/helpers/tags_helper.rb
- app/models/link.rb
- app/models/user.rb
- app/views/cards/_tags.html.slim
早速 #199 を試しにやってみた
気になったこと
- 検閲タグの確認でタグ１つ１つにSQLが発行されてるから最適化したほうが良さそう？
- おそらくN+1問題。多くても10個程度だし、そこまで大きな影響もないのかもしれない
- 任意のタグが入るようになるから、もはや大文字に変換する意味がなさそう？
- ただ同じものだと認識してくれるようが直感的な感じはする
- 稀にバリデーションエラーになってプレビューできなくなる
- 再現性が無くて原因がつかめない...
> panchiraで取得したタグを表示できるようにする

- app/helpers/application_helper.rb
> statementのHTMLエスケープ漏れを回避

- app/assets/stylesheets/custom.scss.erb
- app/views/users/_user_info.html.slim
- Bootstrapのタグ(`.list-group`)自体にスタイル付け足してたとこを独自のクラスに変えた
- 通知のバッジの色が浮いてたのを直した
> ちょっとだけましなcss

- app/views/layouts/_header.html.slim
- app/views/layouts/_user_header.html.slim
> イベント周りのcssを削除、クラス名の指定ミスを修正

- db/seeds.rb
- lib/tasks/tag_task.rake
- test/models/user_test.rb
close: #135 
あとtag_task:initの時代遅れなところもなおした
> seeds.rbをいい感じにした

- app/views/layouts/_user_header.html.slim
> グローバルタイムライン使用時はexploreNav隠す

- app/models/user.rb
- test/models/user_test.rb
> リンクのないオカズがタイムラインに表示されない問題を修正

- app/views/nweets/_home_form.html.slim
- app/views/nweets/_new_form.html.slim
- app/views/nweets/new.html.slim
user_home側のCSS修正したときにnweets/newのほう治すの忘れてた
ついでに横幅も整えた
> nuitaボタンのレイアウトを修正

- .github/workflows/test.yml
- config/database.yml
- db/schema.rb
- test/controllers/users_controller_test.rb
- test/fixtures/nweets.yml
rails db:migrate:resetとかしてもcollate外れないようにする
> デフォルトのcollateを指定

- .github/workflows/test.yml
node_modulesとvendor/bundleをキャッシュするようにする
> Cache CI dependencies

- config/initializers/imageproxy.rb
> hotfix imageproxy

- app/assets/stylesheets/custom.scss.erb
- app/views/users/_calendar.html.slim
> グラフをレスポンシブにする

- README.md
- docker-compose.yml
こうしておくと `docker-compose up` するだけでrailsが上がって嬉しい！
> docker-composeで起動できるようにする。

- app/assets/stylesheets/custom.scss.erb
- app/views/users/_user_info.html.slim
バランスが悪かったのでmargin-topを少し追加してscreen nameのfont-sizeを少し大きくした
> ユーザー名のバランスを調整

- README.md
close #248 
いい感じのREADMEです。（改訂のたびに射精という単語が消えてる気がします）
追加してほしい項目・バッジ、不正確な情報などあればお気軽にご意見ください！
> いい感じのREADME

- app/views/layouts/application.html.slim
related: #266 
トースターの読込できなくなってた
application.js の読み込み遅らせた分トースターの発火も遅らせなきゃだめだったね……
> toastrの表示タイミング遅らせる

- app/assets/stylesheets/custom.scss.erb
- app/frontend/packs/application.ts
- app/frontend/src/header.ts
- app/views/layouts/_header.html.slim
close #206 
スクロール時にヘッダーが隠れるようにした。表示幅が増えていいとおもった
> 下スクロール時にヘッダーを隠す

- app/frontend/src/header.ts
迷ったけど、ちょっとPCだとチカチカして気が散るので一定の画面幅以上で無効にすることにした
> PC操作時はヘッダー隠さない

- app/frontend/src/header.ts
twitterとかブラウザの挙動改めて確認したら、ヘッダー表示する条件ってスクロールをやめることじゃなくて、上方向にスクロールすることだった
ので直した
> navbar現れる条件変える

- README.md
> Fix CI Badge on README.md

- .github/workflows/test.yml
- .gitignore
- Gemfile
- Gemfile.lock
- README.md
- codecov.yml
- test/test_helper.rb
RubyとかRailsをアップデートしたいなあという気持ちになったので、テストをいい感じに増やします。
simplecovを使ってテストカバレッジを計測して、ついでにCIのワークフローにも追加します。
> テストカバレッジを計測する

- app/controllers/users_controller.rb
- config/environments/test.rb
- test/controllers/links_controller_test.rb
- test/controllers/nweets_controller_test.rb
- test/controllers/relationships_controller_test.rb
- test/controllers/twitter_controller_test.rb
- test/controllers/twitters_controller_test.rb
とりあえずテストされていないエンドポイントは無くなったと思うので、最低限のエラー（500出てるページあるとか）には気付けるようになったと思う
simplecovとdeviseの組み合わせの挙動も怪しい(models/user.rb)ので、一旦これでテスト追加は完了にします
> コントローラー関連のテストを追加

- lib/tasks/announces/20201231093122_wrap2020.html
> 2020年まとめ記事を通知に出す

- .github/workflows/rubocop.yml
規則違反があるか確認するだけで、自動修正はしない ([Railsのやつ](https://github.com/rails/rails/blob/master/.github/workflows/rubocop.yml)パクってきただけ)
> CIでRubocop動かす

- app/views/notifications/_notification.html.slim
- test/fixtures/likes.yml
- test/fixtures/notifications.yml
今は急ぎだけど、iconヘルパーの仕様が色々と良くない気がするので修正したい
> 通知画面が500返してた問題を修正

- .rubocop.yml
- .rubocop_todo.yml
- app/controllers/pages_controller.rb
- test/controllers/pages_controller_test.rb
user.global_feedを反映できていませんでした。Rubocop大感謝
> /explore でユーザーのミュートが反映できていなかった問題を修正

- app/frontend/css/application.scss
- app/frontend/css/components/_footer.scss
- app/views/layouts/_footer.html.slim
- app/views/layouts/application.html.slim
- config/locales/views/layouts/ja.yml
データが消えるかも　的な文章を消してシンプルにしました（たぶんもうデータ消えないと思います）
> フッターをリニューアル

- .rubocop.yml
- app/models/nweet.rb
> nweet.rbのコールバックをリファクタリング

- app/frontend/src/header.ts
- app/frontend/src/recommend.ts
header.ts, recommend.ts で対象の要素が存在しなかった場合にreturnするよう設定し、ユーザー用のヘッダーが存在しなくても例外を返さないように修正し、ついでにリファクタリングしました。
> ランディングページ等でJSが動かない問題を修正

- app/views/pages/about.html.slim
- app/views/pages/about.ja.html.slim
- config/routes.rb
> aboutページを追加

- app/frontend/css/_global.scss
- app/frontend/css/_variables.scss
- app/frontend/css/application.scss
- app/frontend/css/cards/_cards.scss
- app/frontend/css/components/_navbar.scss
- app/frontend/css/nweets/_display.scss
- app/frontend/css/nweets/_nweet.scss
- app/frontend/css/nweets/_nweets.scss
- app/frontend/css/nweets/_timeline.scss
- app/helpers/nweets_helper.rb
- app/helpers/pages_helper.rb
- app/views/cards/_card.html.slim
- app/views/devise/registrations/new.html.slim
- app/views/devise/sessions/new.html.slim
- app/views/layouts/_guest_header.html.slim
- app/views/notifications/_notification.html.slim
- app/views/nweets/_display.html.slim
- app/views/nweets/_like_flash.html.slim
- app/views/nweets/_nweet.html.slim
- app/views/pages/_explore_form.html.slim
- app/views/pages/_landing.html.slim
- app/views/pages/_recommend.html.slim
- app/views/pages/_timeline.html.slim
- app/views/pages/about.ja.html.slim
- app/views/pages/explore.html.slim
- app/views/terms/privacy.ja.html.slim
- config/locales/ja.yml
- config/locales/views/cards/ja.yml
- config/locales/views/nweets/ja.yml
- config/locales/views/pages/ja.yml
未ログインのユーザー用のタイムラインのレイアウトを作成しました。
いいね機能やタグ編集機能など、ログイン済みのユーザーが必要なものは改めて実装します。
> ゲスト用の検索結果ページを作成

- app/frontend/css/_utility.scss
- app/frontend/css/_variables.scss
- app/frontend/css/cards/_cards.scss
- app/frontend/css/pages/_sections.scss
- app/views/layouts/_right_section.html.slim
> タイムラインのレイアウトを微調整

- app/frontend/css/_utility.scss
- app/frontend/css/_variables.scss
- app/frontend/css/components/_footer.scss
- app/frontend/css/components/_navbar.scss
- app/frontend/css/components/footers/_guest_footer.scss
- app/frontend/css/components/footers/_user_footer.scss
- app/frontend/css/components/navbars/_user_navbar.scss
- app/frontend/css/nweets/_form.scss
- app/frontend/css/pages/_landing.scss
- app/frontend/packs/application.ts
- app/frontend/src/footer.ts
- app/frontend/src/header.ts
- app/helpers/application_helper.rb
- app/views/layouts/_guest_footer.html.slim
- app/views/layouts/_user_footer.html.slim
- app/views/layouts/_user_header.html.slim
- app/views/layouts/application.html.slim
- app/views/pages/_explore_form.html.slim
- app/views/pages/_landing.html.slim
一定の画面幅以下でフッターが出るようにしました。一番右のプロフィールは今後プロフィール機能のリライトした段階でちゃんと動作するようにします。
> モバイル画面でフッターを表示

- app/views/layouts/_footer_list.html.slim
- config/locales/views/layouts/ja.yml
> 問い合わせフォームをフッターのリンク集に追加

- Gemfile
- Gemfile.lock
- app/assets/javascripts/application.js
- app/views/layouts/application.html.slim
- config/initializers/assets.rb
めちゃくちゃやりたくないんですが、Webpacker経由でのBootstrapの読み込みが何をどう頑張ってもうまく行かないので一時的にsprocketsを復活させました。
Webpacker剥がしてWebpackにするのも含めて将来的にいい感じにしないといけない……
> Bootstrapのdropdownとかが動かないので一時的にsprockets経由で読み込む

- test/controllers/nweets_controller_test.rb
- test/controllers/settings_controller_test.rb
- test/controllers/twitter_controller_test.rb
- test/integration/likeline_test.rb
- test/models/link_test.rb
古くなったテストケースの削除が中心になってしまったので、リニューアル終わったらちゃんと色々追加しないとな……
> リニューアル後の形でテストケース通るように変更

- package.json
- yarn.lock
cf: #359 
自分の場合は`@types/webpack`が抜けてたのが原因っぽい
> package.jsonに@types/webpackを追加

- tsconfig.json
#361  つづき
本番のサーバーに直接入って同じことすると動くのに、cap経由でやると失敗するみたいなことがあってつらい……
これで駄目だったらcapのほうを見直したほうがよさそう
> tsconfigにtypesの記述を追加

- app/views/pages/_empty_feed.html.slim
> settings_pathの変え忘れを修正

- app/frontend/src/modal.ts
モーダル開きまくるとbody直下にDOMが並びまくってキモいかな〜とは思うんですが、それ以外の欠点はまったくないと思うので一旦これで
> 2回同じモーダルが開けない問題に気づいたのでDOMを削除しない

- app/views/layouts/application.html.slim
何も考えずにog:imageにwebpackのURLを指定して無になってたのでS3のURLに変更しました。
> og:imageの画像をS3のURLに差し替え

- README.md
#382 
ただ README.md を書き換えただけです。
> README に書かれてる docker-compose コマンドの修正

- app/frontend/packs/application.ts
- package.json
- yarn.lock
> Turbolinksを再導入

- app/frontend/css/nweets/_nweet.scss
- app/views/nweets/_nweet.html.slim
- app/views/nweets/show.html.slim
要望が多かったので、PC画面でヌイートの詳細日時が表示されるようにしました。
> 一定以上の画面幅でヌイートの詳細時間を表示
